version: "3.9"

services:

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: mypass
      MYSQL_DATABASE: ecommerce_app_database
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: mypass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  authentication-service:
    build: ./server/authentication-service
    container_name: authentication-service
    ports:
      - "7000:7000"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - PORT=7000
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_SCHEMA=ecommerce_app_database
      - DB_USER=mysqluser
      - DB_PASS=mypass
    depends_on:
      - mysql
    restart: unless-stopped

  payment-service:
    build: ./server/payment-service
    container_name: payment-service
    ports:
      - "9050:9050"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - PORT=9050
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_SCHEMA=ecommerce_app_database
      - DB_USER=mysqluser
      - DB_PASS=mypass
    depends_on:
      - mysql
    restart: unless-stopped

  common-data-service:
    build: ./server/common-data-service
    container_name: common-data-service
    ports:
      - "9000:9000"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - PORT=9000
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_SCHEMA=ecommerce_app_database
      - DB_USER=mysqluser
      - DB_PASS=mypass
    depends_on:
      - mysql
    restart: unless-stopped

  client:
    build: ./client
    container_name: ecommerce-client
    ports:
      - "3000:80"
    depends_on:
      - authentication-service
      - payment-service
      - common-data-service
    restart: unless-stopped

volumes:
  mysql_data:
